name: Snyk

on:
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/gradle@master
      with:
        command: monitor
        args: --project-name=@snowplow/roku-tracker
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
